export const env = {
  // MOVIEDB_API_KEY: process.env.REACT_APP_MOVIEDB_API_KEY,
  // MOVIEDB_ACCESS_TOKEN: process.env.REACT_APP_MOVIEDB_ACCESS_TOKEN,

  MOVIEDB_ACCESS_TOKEN:
    "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlYTg3ZTA1NTA0ZjczNWU1MTdkY2ZjYWQ3YTgzZDcyMSIsInN1YiI6IjYxZTQ1NzJlY2EwZTE3MDAxZWU1MGY5YSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.AeQ6zZZSHufC4scXKXu83MYfH5aD218qGPzoJsNnW-Y",
};
